/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kanna-Nakajima (https://sketchfab.com/Kanna-nakajima)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-cat-98da5c4c2fff4c05898ba82c244b9eec
Title: Black cat
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useMotionValue, useSpring } from "motion/react"
import { useFrame } from "@react-three/fiber"

export function Astronaut(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/black_cat.glb')
  const { actions } = useAnimations(animations, group)
  
  useEffect(() => {
    if (animations.length > 0) {
      actions[animations[0].name]?.play()
    }
  }, [actions, animations])

  const yPosition = useMotionValue(5)
  const ySpring = useSpring(yPosition, { damping: 30 })
  
  useEffect(() => {
    ySpring.set(-1)
  }, [ySpring])
  
  useFrame(() => {
    group.current.position.y = ySpring.get()
  })
  
  
  useEffect(() => {
    ySpring.set(-1)
  }, [ySpring])
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
     rotation={[0, -0.1, 0.5]} /*rotation={[-Math.PI /2,Math.PI, 0]} ici le math.pi c est 180 */
      scale={props.scale ||  0.3}
      position={props.position || [1.3,-1,0]}
    >
      <group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface1_cat_0.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlane3_stars_0.geometry}
          material={materials.stars}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/black_cat.glb')